routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MainController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [MainController::class, 'index']
)->name('index');

Route::get('/tovar/{id}', [MainController::class, 'sort']
)->name('sort');

Route::get('/find', function () {
    return view('find');
})->name('find');

Route::get('/find/result', [MainController::class, 'show']
)->name('find-form');

Route::middleware(['auth'])->group(function () {
    Route::resource('admin/tovar', \App\Http\Controllers\AdminController::class, ['parameters' => [
        'tovar' => 'id']]);
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes([
    'register' => false,
    'reset' => false,
    'confirm' => false,
    'verify' => false,
]);

app/Models/Tech.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Tech extends Model
{
    use HasFactory;

    protected $table = "tech";
    public $timestamps = false;

    public function query_build(){
        return DB::table('tech', 't')
            ->join('type_list as tl', 'tl.TypeID', '=', 't.TypeID')
            ->select('t.*', 'tl.*');
    }

    public function AllTovar()
    {
        return $this->query_build()
            ->get();
    }

    public function OneTovar($name)
    {
        return $this->query_build()
            ->where('t.Name', 'like', '%' . $name . '%')
            ->get();
    }

    public function OneTovarById($id)
    {
        return $this->query_build()
            ->Where('t.ID', '=', $id)
            ->get();
    }

    public function Category($id)
    {
        return $this->query_build()
            ->Where('t.TypeID', $id)
            ->get();
    }
}

app/Models/Type_list.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Type_list extends Model
{
    use HasFactory;
    protected $table = "type_list";
    public $timestamps = false;

    public function Types(){
        return DB::table('type_list')->get();
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tech;
use App\Models\Type_list;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class AdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('Admin.index', ['result' => (new Tech)->AllTovar()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Admin.add', ['types' => (new Type_list)->Types()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $add = new Tech;
        $add->Name = $request->input('name');
        $add->Cost = $request->input('cost');
        $add->TypeID = $request->input('type');
        $add->YearID = $request->input('year');
        $add->save();
        return redirect()->route('tovar.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('Admin.info', ['result' => (new Tech)->OneTovarById($id)]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('Admin.edit', ['types' => (new Type_list)->Types(),
            'data' => (new Tech)->OneTovarById($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        DB::table('tech')
            ->where('ID', $id)
            ->update([
                'Name' => $request->input('name'),
                'Cost' => $request->input('cost'),
                'TypeID' => $request->input('type'),
                'YearID' => $request->input('year')]);
        return redirect()->route('tovar.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        DB::table('tech')->where('ID', '=', $id)->delete();
        return redirect()->route('tovar.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/MainController.php
<?php

namespace App\Http\Controllers;

use App\Models\Type_list;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use \App\Models\Tech;
use Illuminate\Support\Facades\DB;

class MainController extends Controller
{
    public function index()
    {
        return view('home', ['result' => (new Tech)->AllTovar(),'types' => (new Type_list)->Types()]);
    }

    public function show(Request $req)
    {
        return view('find', ['result' => (new Tech)->OneTovar($req->input('name'))]);
    }

    public function sort($id)
    {
        return view('home', ['result' => (new Tech())->Category($id),'types' => (new Type_list)->Types()]);
    }
}

resources/views/Admin/add.blade.php
@extends('Admin.layout.schema')

@section('Title','Add')
@section('Content')
    <form action="{{route('tovar.store')}}" method="post">
        @csrf
        <p>
            <input placeholder="Name" type="text" name="name">
        </p>
        <p>
            <input placeholder="Cost" type="text" name="cost">
        </p>
        <p>
            <select name="type" required>
                @foreach($types as $type)
                    <option value='{{ $type->TypeID }}'>{{ $type->NameOfType}}</option>
                @endforeach
            </select>
        </p>
        <p>
            <input placeholder="Year" type="text" name="year">
        </p>
        <p>
        <button type="submit">Add</button>
        <a href="{{route('tovar.index')}}">Back </a>
        </p>
    </form>
@endsection

resources/views/Admin/edit.blade.php
@extends('Admin.layout.schema')
@foreach($data as $row)
@section('Title','Edit '.$row->Name)
@section('Content')
    <form action="{{route('tovar.update',['id'=>$row->ID])}}" method="post">
        <input name="_method" type="hidden" value="PUT">
        @csrf
        <p>
            <input placeholder="Name" type="text" name="name" value="{{$row->Name}}">
        </p>
        <p>
            <input placeholder="Cost" type="text" name="cost" value="{{$row->Cost}}">
        </p>
        <p>
            <select name="type" required>
                @foreach($types as $type)
                    <option value='{{ $type->TypeID }}'>{{ $type->NameOfType}}</option>
                @endforeach
            </select>
        </p>
        <p>
            <input placeholder="Year" type="text" name="year" value="{{$row->YearID}}">
        </p>
        <p>
        <button type="submit">Edit</button>
        <a href="{{route('tovar.index')}}">Back </a>
        </p>
    </form>
@endsection
@endforeach

resources/views/Admin/index.blade.php
@extends('Admin.layout.schema')

@section('Title','Admin')

resources/views/Admin/info.blade.php
@extends('Admin.layout.schema')
@foreach($result as $row)
    @section('Title',$row->Name)
@section('thead')
    <th>Price</th>
    <th>Type</th>
    <th>Year</th>
@endsection
@section('tbody')
    <td> {{$row->Cost}} </td>
    <td> {{$row->NameOfType}} </td>
    <td> {{$row->YearID}} </td>
@endsection
@endforeach

resources/views/Admin/layout/schema.blade.php
<!doctype html>
<html lang="ua">
<head>
    <title>@yield('Title')</title>
    <meta charset="utf-8"/>
    <link rel="stylesheet" type="text/css" href="{{asset('css/app.css')}}">
</head>
<body>
<div class="center">
    <center><h1>Admin Panel</h1>

        <a href="{{route('tovar.index')}}">Main</a>
        <a href="{{route('tovar.create')}}">Add</a>
        <a href="{{ route('logout') }}"
           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
            {{ __('Logout') }}
        </a>

        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
            @csrf
        </form>

    </center>
    @yield('Content')
    @if  (isset($result))
        <table>
            <thead>
            <tr>
                <th>Tovar Name</th>
                @yield('thead')
                <th>Action</th>

            </tr>
            </thead>
            <tbody>

            @foreach ($result as $row)
                <tr>
                    <td> {{$row->Name}} </td>
                    @yield('tbody')
                    <td>
                        <a href="{{route('tovar.show',['id' => $row->ID])}}">More</a>
                        <a href="{{route('tovar.edit',['id' => $row->ID]) }}">Edit</a>
                        <form action="{{ route('tovar.destroy' ,['id' => $row->ID])}}" method="POST">
                            <input name="_method" type="hidden" value="DELETE">
                            {{ csrf_field() }}
                            <button type="submit">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    @endif
</div>
</body>
</html>

resources/views/find.blade.php
@extends('layout.schema')

@section('Title','Find')

@section('Content')
    <p>
    <form action="{{route('find-form')}}">
        @csrf
        <input name="name" id="name" type="text">
        <button id="find" type="submit">Find</button>

        <a href="{{route('index')}}">Back</a>
    </form>
    </p>
@endsection

resources/views/home.blade.php
@extends('layout.schema')

@section('Title','Main')

@section('Content')
    <p>
        <a href="{{route('find')}}">Find</a>|
        <a href="{{ route('login') }}">{{ __('Login') }}</a>
    </p>
    @if(isset($types))
        @foreach($types as $type)
            <a href="{{route('sort',['id'=>$type->TypeID])}}">{{$type->NameOfType}}
                <a>
        @endforeach
    @endif
@endsection

resources/views/layout/schema.blade.php
<!doctype html>
<html lang="ua">
<head>
    <title>@yield('Title')</title>
    <meta charset="utf-8"/>
    <link rel="stylesheet" type="text/css" href="{{asset('css/app.css')}}">
</head>
<body>
<div class="center">
    <center><h1>Magazin electronicu</h1>
        @yield('Content')</center>

    @if (isset($result))
        <table>
            <thead>
            <tr>
                <th>Tovar Name</th>
                <th>Price</th>
                <th>Type</th>
                <th>Year</th>

            </tr>
            </thead>
            <tbody>

            @foreach ($result as $row)
                <tr>
                    <td> {{$row->Name}} </td>
                    <td> {{$row->Cost}} </td>
                    <td> {{$row->NameOfType}} </td>
                    <td> {{$row->YearID}} </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    @endif
</div>
</body>
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif
                            
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>